-- The number of rows in every application table: a restore loads only into a database where it
-- is 0 (ADR 0011 "Backups": "loads it into an empty ... database"). Shared by both engines. A
-- test checks that this list names every table the migrations create.
SELECT
    (SELECT COUNT(*) FROM auth_accounts)
  + (SELECT COUNT(*) FROM auth_opaque_setups)
  + (SELECT COUNT(*) FROM auth_credentials)
  + (SELECT COUNT(*) FROM auth_identity_keys)
  + (SELECT COUNT(*) FROM auth_recovery)
  + (SELECT COUNT(*) FROM auth_bundles)
  + (SELECT COUNT(*) FROM auth_account_states)
  + (SELECT COUNT(*) FROM auth_account_settings)
  + (SELECT COUNT(*) FROM auth_retired_secret_keys)
  + (SELECT COUNT(*) FROM auth_device_certificates)
  + (SELECT COUNT(*) FROM auth_device_revocations)
  + (SELECT COUNT(*) FROM auth_key_grants)
  + (SELECT COUNT(*) FROM auth_sessions)
  + (SELECT COUNT(*) FROM auth_totp_credentials)
  + (SELECT COUNT(*) FROM auth_login_states)
  + (SELECT COUNT(*) FROM auth_device_challenges)
  + (SELECT COUNT(*) FROM auth_rate_limits)
  + (SELECT COUNT(*) FROM auth_pending_recoveries)
  + (SELECT COUNT(*) FROM vault_vaults)
  + (SELECT COUNT(*) FROM vault_self_grants)
  + (SELECT COUNT(*) FROM vault_item_key_wraps)
  + (SELECT COUNT(*) FROM vault_ops)
  + (SELECT COUNT(*) FROM vault_snapshots)
  + (SELECT COUNT(*) FROM vault_compaction_queue)
  + (SELECT COUNT(*) FROM vault_device_cursors)
  + (SELECT COUNT(*) FROM storage_meta)
  + (SELECT COUNT(*) FROM storage_reconciliation)
