//! Identifiers (CRYPTO.md §2, §4.3, §4.4).
//!
//! - **Object ids** are 16 random bytes from the injected CSPRNG, created by whoever creates the
//!   object. They are opaque: no UUID version bits. They are public, so they compare with `==`
//!   and print as hex.
//! - **Symmetric key ids** are derived from the key: `HKDF(K, salt = empty,
//!   LABEL("key-id/symmetric") ‖ 0x00, 16)`, for every symmetric key, generated or derived.
//! - **Public key ids** are `SHA-256(LABEL("key-id") ‖ 0x00 ‖ u8(key_type) ‖ public_key)[0..16]`.

use core::fmt;

use rand_core::CryptoRng;
use sha2::{Digest as _, Sha256};
use subtle::{Choice, ConstantTimeEq};

use crate::error::{DerivationError, ParseError};
use crate::labels;
use crate::secret::Key32;

/// Length of every id and key id.
pub const ID_LEN: usize = 16;

fn write_hex(f: &mut fmt::Formatter<'_>, bytes: &[u8]) -> fmt::Result {
    bytes.iter().try_for_each(|b| write!(f, "{b:02x}"))
}

/// Defines one 16-byte random id type per entry.
macro_rules! random_ids {
    ($( $(#[$doc:meta])* $name:ident; )+) => {$(
        $(#[$doc])*
        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub struct $name([u8; ID_LEN]);

        impl $name {
            /// Draws a fresh id from the injected CSPRNG (CRYPTO.md §2, §12.1).
            #[must_use]
            pub fn generate<R: CryptoRng + ?Sized>(rng: &mut R) -> Self {
                let mut bytes = [0u8; ID_LEN];
                rng.fill_bytes(&mut bytes);
                Self(bytes)
            }

            /// Wraps 16 bytes received from elsewhere (the wire, storage).
            #[must_use]
            pub const fn from_bytes(bytes: [u8; ID_LEN]) -> Self {
                Self(bytes)
            }

            /// Parses an id from exactly 16 bytes.
            ///
            /// # Errors
            /// [`ParseError::InvalidLength`] if `bytes` is not 16 bytes long.
            pub fn from_slice(bytes: &[u8]) -> Result<Self, ParseError> {
                <[u8; ID_LEN]>::try_from(bytes)
                    .map(Self)
                    .map_err(|_| ParseError::InvalidLength)
            }

            /// The id's bytes.
            #[must_use]
            pub const fn as_bytes(&self) -> &[u8; ID_LEN] {
                &self.0
            }

            /// The id's bytes, by value.
            #[must_use]
            pub const fn to_bytes(self) -> [u8; ID_LEN] {
                self.0
            }
        }

        impl AsRef<[u8]> for $name {
            fn as_ref(&self) -> &[u8] {
                &self.0
            }
        }

        impl fmt::Debug for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str(concat!(stringify!($name), "("))?;
                write_hex(f, &self.0)?;
                f.write_str(")")
            }
        }
    )+};
}

random_ids! {
    /// `account_id`. Also the OPAQUE `credential_identifier` of a real account (§5.3).
    AccountId;
    /// `device_id`.
    DeviceId;
    /// `vault_id`.
    VaultId;
    /// `item_id`.
    ItemId;
    /// `op_id` of a sync op.
    OpId;
    /// `snapshot_id` of an item snapshot.
    SnapshotId;
    /// `attachment_id` (M3).
    AttachmentId;
    /// `share_id` (M5). Also the salt of the share derivations (§4.3).
    ShareId;
    /// `message_id` of a stored mail message (M6).
    MessageId;
    /// `pairing_id` (M4).
    PairingId;
    /// `transfer_id` of a re-sync transfer (M4).
    TransferId;
    /// `export_id` of an encrypted export (§11.14).
    ExportId;
    /// `backup_id` of a server-secrets backup (§5.11). Generated by the server.
    BackupId;
    /// `login_id` of a pending OPAQUE login (§5.10). Generated by the server.
    LoginId;
    /// `session_id` of a device-authenticated session (§5.10). Generated by the server.
    SessionId;
}

/// The id of a symmetric key, derived from the key (CRYPTO.md §4.3, §4.4):
/// `HKDF(ikm = K, salt = empty, info = LABEL("key-id/symmetric") ‖ 0x00, 16)`.
///
/// It goes in envelope headers so a reader can find the key; the reader derives the id of each
/// key it holds and compares. Because it is derived from a secret, equality is constant-time.
#[derive(Clone, Copy, Eq)]
pub struct SymmetricKeyId([u8; ID_LEN]);

impl SymmetricKeyId {
    /// Derives the id of `key`.
    ///
    /// # Errors
    /// [`DerivationError`], which cannot happen for this fixed output length.
    pub fn derive(key: &Key32) -> Result<Self, DerivationError> {
        let mut id = [0u8; ID_LEN];
        crate::kdf::hkdf_sha256(
            key.expose_secret(),
            None,
            labels::KEY_ID_SYMMETRIC,
            &[],
            &mut id,
        )?;
        Ok(Self(id))
    }

    /// Wraps 16 key-id bytes read from an envelope header or a signed statement.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; ID_LEN]) -> Self {
        Self(bytes)
    }

    /// The id's bytes.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; ID_LEN] {
        &self.0
    }
}

impl ConstantTimeEq for SymmetricKeyId {
    fn ct_eq(&self, other: &Self) -> Choice {
        self.0.ct_eq(&other.0)
    }
}

impl PartialEq for SymmetricKeyId {
    /// Constant-time (CRYPTO.md §12.3).
    fn eq(&self, other: &Self) -> bool {
        self.ct_eq(other).into()
    }
}

impl core::hash::Hash for SymmetricKeyId {
    fn hash<H: core::hash::Hasher>(&self, state: &mut H) {
        self.0.hash(state);
    }
}

impl fmt::Debug for SymmetricKeyId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("SymmetricKeyId(")?;
        write_hex(f, &self.0)?;
        f.write_str(")")
    }
}

/// Public key types (CRYPTO.md §4.4). `0x10`–`0x1F` are reserved for post-quantum keys and
/// are rejected until they are specified.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u8)]
#[non_exhaustive]
pub enum KeyType {
    /// Identity Ed25519 signing key.
    IdentityEd25519 = 0x01,
    /// Identity X25519 key (HPKE `0x10`).
    IdentityX25519 = 0x02,
    /// Mail X25519 key (M6).
    MailX25519 = 0x03,
    /// Device Ed25519 signing key.
    DeviceEd25519 = 0x04,
    /// Device X25519 key.
    DeviceX25519 = 0x05,
}

impl KeyType {
    /// Every defined key type.
    pub const ALL: [Self; 5] = [
        Self::IdentityEd25519,
        Self::IdentityX25519,
        Self::MailX25519,
        Self::DeviceEd25519,
        Self::DeviceX25519,
    ];

    /// The `u8` encoding.
    #[must_use]
    pub const fn to_u8(self) -> u8 {
        self as u8
    }

    /// Parses a `key_type` byte.
    ///
    /// # Errors
    /// [`ParseError::InvalidValue`] for `0x00`, the reserved post-quantum range `0x10`–`0x1F`
    /// and every other undefined value.
    pub const fn from_u8(value: u8) -> Result<Self, ParseError> {
        match value {
            0x01 => Ok(Self::IdentityEd25519),
            0x02 => Ok(Self::IdentityX25519),
            0x03 => Ok(Self::MailX25519),
            0x04 => Ok(Self::DeviceEd25519),
            0x05 => Ok(Self::DeviceX25519),
            _ => Err(ParseError::InvalidValue),
        }
    }
}

/// Length of every public key of the M1 key types (Ed25519 and X25519).
pub const PUBLIC_KEY_LEN: usize = 32;

/// The id of a public key (CRYPTO.md §4.3):
/// `SHA-256(LABEL("key-id") ‖ 0x00 ‖ u8(key_type) ‖ public_key)[0..16]`.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct PublicKeyId([u8; ID_LEN]);

impl PublicKeyId {
    /// Derives the id of a public key of the given type.
    #[must_use]
    pub fn derive(key_type: KeyType, public_key: &[u8; PUBLIC_KEY_LEN]) -> Self {
        let digest = Sha256::new()
            .chain_update(labels::KEY_ID.as_bytes())
            .chain_update([0x00, key_type.to_u8()])
            .chain_update(public_key)
            .finalize();
        let mut id = [0u8; ID_LEN];
        id.copy_from_slice(&digest[..ID_LEN]);
        Self(id)
    }

    /// Wraps 16 key-id bytes read from a header, container or statement.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; ID_LEN]) -> Self {
        Self(bytes)
    }

    /// The id's bytes.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; ID_LEN] {
        &self.0
    }
}

impl fmt::Debug for PublicKeyId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("PublicKeyId(")?;
        write_hex(f, &self.0)?;
        f.write_str(")")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_util::{hex, seeded_rng};

    #[test]
    fn random_ids_come_from_the_injected_rng() {
        let a = AccountId::generate(&mut seeded_rng(3));
        let b = AccountId::generate(&mut seeded_rng(3));
        assert_eq!(a, b);
        let mut rng = seeded_rng(3);
        let first = DeviceId::generate(&mut rng);
        let second = DeviceId::generate(&mut rng);
        assert_ne!(first, second);
        assert_eq!(first.as_bytes(), a.as_bytes());
    }

    #[test]
    fn id_parsing_and_debug() {
        let id = VaultId::from_slice(&[0xab; 16]).unwrap();
        assert_eq!(id.to_bytes(), [0xab; 16]);
        assert_eq!(id.as_ref(), &[0xab; 16]);
        assert_eq!(
            format!("{id:?}"),
            "VaultId(abababababababababababababababab)"
        );
        assert_eq!(ItemId::from_slice(&[0; 15]), Err(ParseError::InvalidLength));
        assert_eq!(ItemId::from_slice(&[0; 17]), Err(ParseError::InvalidLength));
    }

    #[test]
    fn symmetric_key_id_is_hkdf_of_the_key() {
        // Independent computation: HKDF-SHA-256 with a zero-length salt (RFC 5869: HashLen
        // zeros), info = "rizzy-vault/v1/key-id/symmetric" || 0x00, L = 16.
        let key = Key32::from_slice(&[0x11; 32]).unwrap();
        let mut expected = [0u8; 16];
        hkdf::Hkdf::<Sha256>::new(Some(&[0u8; 32]), &[0x11; 32])
            .expand(b"rizzy-vault/v1/key-id/symmetric\x00", &mut expected)
            .unwrap();
        let id = SymmetricKeyId::derive(&key).unwrap();
        assert_eq!(id.as_bytes(), &expected);
        assert_eq!(key.key_id().unwrap(), id);
        // L = 16 is the first 16 bytes of the L = 32 output (HKDF-Expand T(1)).
        let mut long = [0u8; 32];
        hkdf::Hkdf::<Sha256>::new(None, &[0x11; 32])
            .expand(b"rizzy-vault/v1/key-id/symmetric\x00", &mut long)
            .unwrap();
        assert_eq!(&long[..16], id.as_bytes());
        // Known answer, computed independently with Python `cryptography` 41.0.7
        // (`HKDF(SHA256(), length=16, salt=None, info=b"rizzy-vault/v1/key-id/symmetric\0")`)
        // and cross-checked with Python's `hmac` module.
        assert_eq!(id.as_bytes().as_slice(), hex(KEY_ID_OF_0X11).as_slice());
    }

    const KEY_ID_OF_0X11: &str = "3961f732bceb9056d953baad8dbfaecf";

    #[test]
    fn symmetric_key_ids_differ_per_key_and_compare_by_value() {
        let a = Key32::from_slice(&[1; 32]).unwrap().key_id().unwrap();
        let b = Key32::from_slice(&[2; 32]).unwrap().key_id().unwrap();
        assert_ne!(a, b);
        assert_eq!(a, SymmetricKeyId::from_bytes(*a.as_bytes()));
        assert!(bool::from(
            a.ct_eq(&SymmetricKeyId::from_bytes(*a.as_bytes()))
        ));
        assert!(format!("{a:?}").starts_with("SymmetricKeyId("));
    }

    #[test]
    fn public_key_id_layout() {
        let pk = [0x5a; 32];
        let mut msg = b"rizzy-vault/v1/key-id\x00".to_vec();
        msg.push(0x04);
        msg.extend_from_slice(&pk);
        let digest = Sha256::digest(&msg);
        let id = PublicKeyId::derive(KeyType::DeviceEd25519, &pk);
        assert_eq!(id.as_bytes(), &digest[..16]);
        // The key type is bound: same bytes, different type, different id.
        assert_ne!(id, PublicKeyId::derive(KeyType::DeviceX25519, &pk));
    }

    #[test]
    fn key_types_round_trip_and_reserved_values_are_rejected() {
        for kt in KeyType::ALL {
            assert_eq!(KeyType::from_u8(kt.to_u8()), Ok(kt));
        }
        for v in [0x00, 0x06, 0x0f, 0x10, 0x15, 0x1f, 0x20, 0xff] {
            assert_eq!(KeyType::from_u8(v), Err(ParseError::InvalidValue), "{v:#x}");
        }
    }
}
